Repository pagopa/cstar-securehub-infra-api-spec, pull requests merged in 2025-09, with the labels that each got.

#57 feat: [UPBE-85] Creazione policy e validazione token
  src/idpay/21_apim_api_portal_users.tf
  src/idpay/99_locals.tf
  src/idpay/99_variables.tf
  src/idpay/apim/api_product/portal_users_api/policy_users_portal.xml.tpl
  src/idpay/env/itn-dev/terraform.tfvars
  src/idpay/env/itn-prod/terraform.tfvars
  src/idpay/env/itn-uat/terraform.tfvars
Labels: applied dev, applied uat, applied prod

#61 feat: [EBE-108] preview payment
  src/idpay/20_apim_api_portal_merchants_op.tf
  src/idpay/apim/api/idpay_merchants_op_portal/openapi.merchants.op.portal.yml
  src/idpay/apim/api/idpay_merchants_op_portal/put-payment-bar-code-preview-trxcode-policy.xml.tpl
Labels: applied dev, applied uat, applied prod

#62 feat: [SRTP-744] add api policy to identify subject in JWT
  src/srtp/99_locals.tf
  src/srtp/api/pagopa/payees_registry_get_policy.xml
  src/srtp/api/pagopa/service_providers_registry_get_policy.xml
  src/srtp/api_fragment/registry-access-logger.xml
Labels: enhancement, oer, applied dev, applied uat, applied prod

#70 fix: [SRTP-434] Return error body as specified
  src/srtp/api/pagopa/service_providers_registry.yaml
Labels: applied dev, applied uat, applied prod

#71 chore: [EBE-159] change path for policy
  src/idpay/apim/api/idpay_merchants_portal/get-pos-transactions-progress-policy.xml.tpl
Labels: applied dev, applied uat, applied prod

#76 feat: EBE-158 update policy merchant op
  src/idpay/apim/api_product/portal_merchants_op_api/policy_merchants_op_portal.xml.tpl
Labels: applied dev

#84 feat: [UPBE-127] inserimento policy onboarding detail
  src/idpay/apim/api/idpay_appio_full/openapi.appio.full.yml
  src/idpay/apim/api/idpay_onboarding_workflow/get-initiative-details-policy.xml.tpl
  src/idpay/apim/api/idpay_onboarding_workflow/openapi.onboarding.yml
  src/idpay/apim/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
Labels: applied dev, applied uat, applied prod, idpay

#91 fix: add formal motivation
  src/idpay/apim/api/idpay_asset_register/openapi.register.yml
Labels: applied dev, applied uat, applied prod, idpay

#94 fix: EBE-187 api confirm payment
  src/idpay/20_apim_api_portal_merchants_op.tf
  src/idpay/apim/api/idpay_merchants_op_portal/openapi.merchants.op.portal.yml
  src/idpay/apim/api/idpay_merchants_op_portal/put-capture-payment-policy.xml.tpl
Labels: applied dev

#97 feat: Change selfcare endpoint & update modules
  .terraform-version
  scripts/terraform_run_all.sh
  src/idpay/.terraform.lock.hcl
  src/idpay/20_apim_api_token_exchange.tf
  src/idpay/20_apim_api_token_exchange_merchants.tf
  src/idpay/99_locals.tf
  src/idpay/99_main.tf
  src/mcshared/.terraform.lock.hcl
  src/mcshared/99_main.tf
  src/srtp/.terraform.lock.hcl
  src/srtp/99_main.tf
Labels: applied dev, applied uat, applied prod

#92 feat: [RDB-274] adding model and brand to products api filter and sort
  src/idpay/apim/api/idpay_asset_register/openapi.register.yml
Labels: applied dev

#100 feat: [EBE-208] updated swagger and removed policy from merchant portal
  src/idpay/21_apim_api_portal_merchants.tf
  src/idpay/apim/api/idpay_merchants_op_portal/openapi.merchants.op.portal.yml
  src/idpay/apim/api/idpay_merchants_portal/get-pos-transactions-progress-policy.xml.tpl
  src/idpay/apim/api/idpay_merchants_portal/openapi.merchants.portal.yml
Labels: applied dev

#103 chore: [EBE_217] Adjusted minimum value to accept negatives
  src/idpay/apim/api/idpay_merchants_portal/openapi.merchants.portal.yml
Labels: applied dev

#102 feat: [UPBE-218] added generate transaction PDF API
  src/idpay/21_apim_api_portal_users.tf
  src/idpay/apim/api/idpay_appio_full/openapi.appio.full.yml
  src/idpay/apim/api/idpay_payment_io/get-generate-pdf-barcode-web-policy.xml.tpl
  src/idpay/apim/api/idpay_payment_io/openapi.payment_io.yml.tpl
  src/idpay/apim/api/idpay_timeline/get-timeline-detail-web-policy.xml.tpl
Labels: applied dev, applied uat, idpay
